### ISSUE TITLE
Game crash, configurator on augpack.

### ISSUE THREAD

**Issue by hugojmaia** [zetaPRIME/sb.StardustSuite#15]
I was doing a mission and tried putting my wings epp into the augpack while in the sphere form from the nanofield.
Right after clicking the wings into the epp slot the interface closed, my wings turned orange and were sent to the wrong tab in my inventory. Their name turned into "Geode".
Upon trying to pick them up my game crashed.
Game log:
[starbound.log](https://github.com/zetaPRIME/sb.StardustSuite/files/6557127/starbound.log)

**Comment by hugojmaia** [comment]
![image](https://user-images.githubusercontent.com/8614893/119906267-43135380-bf24-11eb-8262-b13e6e47c056.png)
How it ended looking, picking it up crashed the game. After the game crashed, picking it back up fixed the item.

**Comment by zetaPRIME** [comment]
I uh. have *no* clue here??

**Comment by zetaPRIME** [comment]
as it turns out, this is from how metaGUI checks for the shift key going wrong because items were suppressed. has been fixed for a couple releases.
