### ISSUE TITLE
Pulse Rifle Tactical Shot specialization

### ISSUE THREAD

**Issue by hugojmaia** [zetaPRIME/sb.StardustSuite#17]
On the description of this specialization it says it disables automatic fire.
That is not happening.

**Comment by hugojmaia** [comment]
![image](https://user-images.githubusercontent.com/8614893/125835327-e7d7a178-08a3-4360-b5a5-e583fd82fa9d.png)
![image](https://user-images.githubusercontent.com/8614893/125835163-e4002861-edfa-40ea-8328-535727030cca.png)
![image](https://user-images.githubusercontent.com/8614893/125835393-425f0130-d701-42f4-8784-ca6e7a1922e6.png)
There seems to be a disagreement between the tooltip and the upgrade interface.
With no specialization selected they match, with either specialization selected the gun reports a 10% damage increase.
I'll get a punchy to test which one is correct.

**Comment by zetaPRIME** [comment]
Fixed autofire and clarified tooltip difference in [Beta v0.1.5c](https://github.com/zetaPRIME/sb.StardustSuite/releases/tag/beta-v0.1.5c).
