### ISSUE TITLE
Could not load image asset '/metagui/themes/frackin/v2/...

### ISSUE THREAD

**Issue by ulrellik** [zetaPRIME/sb.StardustSuite#24]
Hi, I often see those errors popping up in the log:

> [13:05:50.834] [Error] Could not load image asset '/metagui/themes/frackin/v2/frame.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/frame.png'
> [13:05:50.837] [Error] Could not load image asset '/metagui/themes/frackin/v2/panel.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/panel.png'
> [13:05:50.840] [Error] Could not load image asset '/metagui/themes/frackin/v2/button.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/button.png'
> [13:05:50.842] [Error] Could not load image asset '/metagui/themes/frackin/v2/scrollBar.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/scrollBar.png'
> [13:05:50.844] [Error] Could not load image asset '/metagui/themes/frackin/v2/textBox.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/textBox.png'
> [13:05:50.847] [Error] Could not load image asset '/metagui/themes/frackin/v2/tabPanel.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/tabPanel.png'
> [13:05:50.849] [Error] Could not load image asset '/metagui/themes/frackin/v2/tab.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/tab.png'
> [13:05:50.851] [Error] Could not load image asset '/metagui/themes/frackin/v2/checkBox.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/checkBox.png'
> [13:05:50.853] [Error] Could not load image asset '/metagui/themes/frackin/v2/radioButton.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/radioButton.png'
> [13:05:50.856] [Error] Could not load image asset '/metagui/themes/frackin/v2/itemSlot.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/itemSlot.png'
> [13:05:50.858] [Error] Could not load image asset '/metagui/themes/frackin/v2/itemRarity.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/itemRarity.png'
> [13:05:50.858] [Error] Could not load image asset '/metagui/themes/frackin/itemRarity.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/itemRarity.png'
> [13:05:50.867] [Error] Could not load image asset '/metagui/themes/frackin/v2/windowBg.png', using placeholder default.
> (AssetException) No such asset '/metagui/themes/frackin/v2/windowBg.png'

[starbound.log](https://github.com/zetaPRIME/sb.StardustSuite/files/7449461/starbound.log)

I don't think those are problematic errors, as there exists fallbacks. I suppose the errors come, because this theme doesn't haven't any specific files for elements under `/metagui/themes/frackin/v2/`. Anyways, just wanted to let you know :-)

**Comment by zetaPRIME** [comment]
Expected behavior. Currently have no way to check for an image's existence without causing an error message.
