### ISSUE TITLE
Transmatter terminal creating client side lag

### ISSUE THREAD

**Issue by PsionicArchon** [zetaPRIME/sb.StardustSuite#3]
My client lags when ever I am accessing the transmatter terminal. 

I'm assuming that it's simply polling too frequently, creating excessive render updates.

I am using the latest version of StarTech on version 1.3.1 of Starbound.

**Comment by zetaPRIME** [comment]
Already fixed as of https://github.com/zetaPRIME/sb.StardustSuite/commit/79012963c5f9c1b22eb6380b54c13260d225a7db
