### ISSUE TITLE
Abandoned? License?

### ISSUE THREAD

**Issue by ShaneCourtrille** [zetaPRIME/sb.StardustSuite#8]
Wondering if this has been abandoned and if so any interest in licensing it such that someone can keep it going if they wanted?

**Comment by zetaPRIME** [comment]
oh right, I should probably get around to adding a license at some point!

as for being abandoned, nope; just been busy with a bunch of other projects lately. going to be rewriting the drive bays as soon as I get back to this, and thus finally get rid of the data loss issue that's been plaguing this since... well, always.

**Comment by ShaneCourtrille** [comment]
Any interest in PRs?  Would prediscuss of course but want to know the if I
should spend time learning the code.

**Comment by zetaPRIME** [comment]
hmm... we'll have to see about that; I have some Big Things planned, direction-wise, and thus I'm probably going to be kind of picky about things until my vision is more complete. (moreso with features and gameplay changes than bugfixes, of course)

**Comment by ShaneCourtrille** [comment]
Makes sense.  Coming from playing a lot of heavily modified Minecraft I'm
just getting so damn tired of the limitations that exist in inventory
management today but didn't want to have to rebuild everything from scratch
myself.  Good luck and looking forward to your bug squashing so I can
switch over :D

**Comment by zetaPRIME** [comment]
For now you can just use storage buses hooked up to big inventories; those 2x1 (or 1x2) lockers from Enhanced Storage (I think?) bumped up to 300 slots each works a charm.

**Comment by ShaneCourtrille** [comment]
That's what I'm doing today (we're using FrakinU) but then I have multiples
of the same item spread across different chests making my inventory
interface a mess.. ugh..

**Comment by zetaPRIME** [comment]
License added in d70ced2fd4bf917ff0f597aa9afba14c921532f8.
